//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicles_Reservation_System.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BOOKING__ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int CAR_ID { get; set; }
        public System.DateTime BOOKING_DATE { get; set; }
        public double AMOUNT_DUE { get; set; }
        public System.DateTime RETURN_DATE { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
