//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicles_Reservation_System.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int CAR_ID { get; set; }
        public string CAR_NAME { get; set; }
        public string CATEGORY { get; set; }
        public string COLOR { get; set; }
        public string MFG_DATE { get; set; }
        public double INSURANCE_NO { get; set; }
        public string REG_NO { get; set; }
        public string STATUS { get; set; }
        public double RATE_PER_DAY { get; set; }
        public System.DateTime DATE_OF_INCLUSION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
