//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicles_Reservation_System.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryOperator
    {
        public string UNAME { get; set; }
        public string PWORD { get; set; }
        public string ENTRYOP_NAME { get; set; }
    }
}
